### ISSUE TITLE
GET http://host/info 404 (Not Found)

### ISSUE THREAD

**Issue by IvanPitrov** [pxlsspace/Pxls#149]
Hello, I install site to VPS. In installatio process do all by instruction. By after start my site, see only "Loading..." and refreshing page. After, I open f12, and open "Console" page. On the page 1 error about GET http://host/info 404 (Not Found). I dont know, but maybe site don`t work because this error? Or maybe someone can help me?

**Comment by FlyingSixtySix** [comment]
Interesting. Have you set the `host` configuration variable seen [here](https://github.com/xSke/Pxls/blob/c77d648e10a0819a1293dacad04293b8294b3715/resources/reference.conf#L84)?

**Comment by IvanPitrov** [comment]
> Interesting. Have you set the `host` configuration variable seen [here](https://github.com/xSke/Pxls/blob/c77d648e10a0819a1293dacad04293b8294b3715/resources/reference.conf#L84)?

Sorry, last update of this project work on you server?

**Comment by FlyingSixtySix** [comment]
> Sorry, last update of this project work on you server?

Yeah, it's working on my side.

**Comment by IvanPitrov** [comment]
> > Sorry, last update of this project work on you server?
> 
> Yeah, it's working on my side.

Oh, so strange. Thanks for your reply.

**Comment by IvanPitrov** [comment]
> > Sorry, last update of this project work on you server?
> 
> Yeah, it's working on my side.

Sorry, another question, which variable should be set to the host parameter?

**Comment by FlyingSixtySix** [comment]
> Sorry, another question, which variable should be set to the host parameter?
I just set it to be localhost.

**Comment by FlyingSixtySix** [comment]
> Without any port?
With the port I'm running it on appended. Like `localhost:4567` if using default port.

**Comment by Sorunome** [comment]
You should set it to the address publicly available, so for example we have set it to `pxls.space`

**Comment by IvanPitrov** [comment]
> You should set it to the address publicly available, so for example we have set it to `pxls.space`

I have connected domain pxls.ml

**Comment by dylanrenwick** [comment]
@IvanPitrov is that the domain you're accessing your pxls clone from? If so set `host` to that.
Did you get this working?
