### ISSUE TITLE
Doesn't place pixels...

### ISSUE THREAD

**Issue by TechAdvancedCyborg** [pxlsspace/Pxls#199]
The pixels appeared placed but when I reload the page they disappear...

I looked in the Network tab (F12) and there were two requests made when I placed a pixel:
- First one
URL: https://www.google-analytics.com/r/collect?v=1&_v=j77&a=1856512990&t=event&_s=3&dl=https://pxls.space/&ul=fr&de=UTF-8&dt=pxls.space&sd=24-bit&sr=1920x1080&vp=1920x1006&je=0&ec=Pixels&ea=Place&_u=CACAAEAB~&jid=1048081259&gjid=1603347960&cid=737208562.1544910788&tid=UA-96985737-1&_gid=123860878.1562010634&_r=1&z=743430816
- Second one
URL: https://stats.g.doubleclick.net/r/collect?v=1&aip=1&t=dc&_r=3&tid=UA-96985737-1&cid=737208562.1544910788&jid=1048081259&_gid=123860878.1562010634&gjid=1603347960&_v=j77&z=743430816

These urls are trackers...

**Comment by FlyingSixtySix** [comment]
You appear to have been shadowbanned. Submit an appeal [here](https://pxls.space/appeal).
