### ISSUE TITLE
Running Without Auth

### ISSUE THREAD

**Issue by aneurinprice** [pxlsspace/Pxls#203]
Hi guys,

I am currently putting together a docker container for Pxls and intend to run it at a LAN event with 100+ people attending. I am no java developer however. Is it possible to run this WITHOUT auth? I intend on running this privately on the LAN so spammers/bots are not a problem for us. If you could let me know, that would be much appreciated. My work will be on my gitlab. If/ when I am happy with my container I will PR.

**Comment by FlyingSixtySix** [comment]
For the most part, yes. In your `pxls.conf`, under `oauth`, set `useIp` to true. This will disable the need to authenticate users via third-part services, but instead authenticate based on IP address.

Normal users will not be able to see IP addresses in lookups— only IP addresses marked with `MODERATOR` role+ can. On the subject, I’m not entirely sure how it will handle other users on the same network; they may fall under the same IP address.

**Comment by TechAdvancedCyborg** [comment]
If it's a LAN event you can probably ask the participants to run a VPN server on a computer at their house.

**Comment by TechAdvancedCyborg** [comment]
I recommend [OpenVPN]( https://github.com/OpenVPN/openvpn)
