### ISSUE TITLE
Update welcome box to describe the game

### ISSUE THREAD

**Issue by FlyingSixtySix** [pxlsspace/Pxls#212]
![2019-09-09-Welcome-Box](https://user-images.githubusercontent.com/19217244/64528387-a3093700-d308-11e9-9226-3c9e2b5af085.PNG)
The welcome box currently doesn't describe the game or how it works.

**Comment by GlowingSocc** [comment]
Closed in f3941660698a208d98df9ae754d024ffd89c6665
