### ISSUE TITLE
Tutorial?

### ISSUE THREAD

**Issue by JewishLewish** [pxlsspace/Pxls#349]
So I tried to do the exact steps but their are times where it won't let me do it.

Example, I cannot do git clone because it said "access denied"

**Comment by FlyingSixtySix** [comment]
Try running this:

`git clone https://github.com/pxlsspace/Pxls`

**Comment by cp-codes2** [comment]
adding on to this perhaps if a dev could find the time to do it, a video tutorial on getting a instance running would be nice. especially for people like me who dont have much experience running things like this and need a little extra help.

**Comment by spark1313** [comment]
As mentioned in #423, this will track a video tutorial while #423 will be for a text-based instructional/tutorial.

**Comment by spark1313** [comment]
@FlyingSixtySix Can you rename this issue to "Video Tutorial Creation" or something similar?
