### ISSUE TITLE
Please Tutorial

### ISSUE THREAD

**Issue by PoultyHoll** [pxlsspace/Pxls#423]
Is there a tutorial on YouTube? Tried it many times, but it always gives errors (

**Comment by Titeiiko** [comment]
Vouch, I feel like there should a tutorial aswell.

Mika claimed that she will make one in the future but it would nice to have it as soon as possible

**Comment by spark1313** [comment]
This was again requested today in Discord by TheKingElessar.

**Comment by spark1313** [comment]
This to some degree clones previous #349. I'll fragment the work for this one into a text-based instructional/wiki tutorial with #349 for a video tutorial.

A nice place for a text-based instructional would be on the Wiki tab, which could also break out and expand the repo readme, pending @FlyingSixtySix thoughts.

**Comment by zulujive** [comment]
> Is there a tutorial on YouTube? Tried it many times, but it always gives errors (

https://blog.lukeroszmann.com/2023/03/hosting-pxlsspace-part-1-basics.html

I'm working on a series of blogs about doing this. Please feel free to reach out for any help! I'll probably get some videos going as well here soon
