### ISSUE TITLE
Fix Broken Discord Webhooks

### ISSUE THREAD

**Issue by spark1313** [pxlsspace/Pxls#496]
Webhooks for the #development channel in Discord are not all working.

I saw notifications recently come in from the PxlsStats, PxlsBot, PxlsAdmin repos but confirming not from the Pxls repo.

I don't believe they came in from the PxlsApp or pxls-markdown repos either if configured or intended.

**Comment by FlyingSixtySix** [comment]
Added org-wide webhook; if private repositories are caught in it then I'll go back to repository-specific hooks.
