### ISSUE TITLE
Chat flicker

### ISSUE THREAD

**Issue by Seon82** [pxlsspace/Pxls#509]
When the number of messages received exceeds the value set in `chat.truncate.max`, messages start flickering (foreground and background colors getting swapped every time a new message is received).

Problem seems to be with this [line](https://github.com/pxlsspace/Pxls/blob/87d87d51944f330cd20d3df87bb28740151e0ac8/resources/public/pxls.js#L5415), causing the odd and even messages to switch around. Removing old messages by groups of two might be a viable solution.

**Comment by kimikanna** [comment]
https://github.com/pxlsspace/Pxls/pull/591 
i think i fixed it by changing 0 to 1
