### ISSUE TITLE
SSL/TLS?

### ISSUE THREAD

**Issue by zulujive** [pxlsspace/Pxls#632]
Anyone figured out a way to do SSL/TLS on your server? I'd like to prevent any user data going out in the open. I'm going to figure this out anyways (hopefully), but shortcuts and tips are appreciated.

**Comment by spark1313** [comment]
Hi @zulujive,

Have you looked into installing nginx and configuring it to serve as a reverse proxy for your host?
https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/

Alongside that, you could implement LetsEncrypt for a free SSL/TLS solution.
Certbot is a common LetsEncrypt implementation software I've used before which worked fairly well.
https://certbot.eff.org/
