### ISSUE TITLE
Staff Broadcast?

### ISSUE THREAD

**Issue by zulujive** [pxlsspace/Pxls#633]
In the roles.conf file, staff have a permission called "user.receivestaffbroadcasts"

How do I use this? Also, is there an admin panel or is that still in the works?

**Comment by FlyingSixtySix** [comment]
The `user.receivestaffbroadcasts` permission grants users the ability to see new messages from shadow-banned users and view profiles of users during snip mode.

An admin panel is available at https://github.com/pxlsspace/PxlsAdmin, but fair word of warning, it's held together by duct tape and string.

**Comment by zulujive** [comment]
Thank you! Final question:
How do I view chat reports? They kinda just fall right into the database with no way to access them.
