### ISSUE TITLE
"addnotification" Spaces Issue

### ISSUE THREAD

**Issue by zulujive** [pxlsspace/Pxls#636]
When I use the `addnotification` command with (Title) (Expiry) (Body), the body will be cut off if a space is used. Is there a way around this without using underscore, like an open and close tag that I'm missing?

**Comment by spark1313** [comment]
Hi @zulujive,

Not quite sure what the referenced command is for (pxls UI command?) but CLI commands in general are commonly put in single or double quotes as markers to encapsulate strings or other variables which may have a space in them. There also may be the option to escape each space with an escape character like \ if quotes do not work, although that can be much more of a pain.

Let me know if this works out.

**Comment by zulujive** [comment]
> Hi @zulujive,
> 
> Not quite sure what the referenced command is for (pxls UI command?) but CLI commands in general are commonly put in single or double quotes as markers to encapsulate strings or other variables which may have a space in them. There also may be the option to escape each space with an escape character like \ if quotes do not work, although that can be much more of a pain.
> 
> Let me know if this works out.

@spark1313 It didn't work doing that either. I'm using CLI commands because the admin panel was already barely hanging on a couple of years ago. At some point I might try making a simple python-based admin panel, but I don't need it enough right now to justify taking on a project like that. I tried double quotes the "\", the only thing that seems to work are underscores. I'll be doing some more tests, hopefully something comes up.

**Comment by zulujive** [comment]
@spark1313 Hello?

**Comment by spark1313** [comment]
Hi @zulujive,

I'm not sure why double quotes may not work. However, I have not personally set up this stack before. Can you please provide some more info like a screenshot and details which CLI you are using along with a command example?
