### ISSUE TITLE
Browser history bloat 

### ISSUE THREAD

**Issue by Kompas9** [pxlsspace/Pxls#670]
Is there a work around of filling browsers history with unnecessary URL's after every move in canvas ? Just after 4 days, we had ~20k records in, slowing down browsers UI to the halt. (history file manage to get +600mb)

**Comment by BlankParenthesis** [comment]
I thought there was a mechanism which prevented this. If I find time I'll look into it: it's not supposed to append history for every move.

**Comment by Kompas9** [comment]
Is query.js even called in index.html, from what I can seem it's not included in (manually adding it throws out error)
