### ISSUE TITLE
Is it possible to get the nginx template and pxls.conf to go out to the global network? (question)

### ISSUE THREAD

**Issue by bbdcdanilko** [pxlsspace/Pxls#673]
The bottom line is that 127.0.0.1:4567 and localhost:4567, nginx does not want to target and release to the Internet

I found 2 issue before, but they do not solve the problem, I really don’t understand how to work with a java application

**Comment by BlankParenthesis** [comment]
Can you elaborate what your setup is?
Typically, you would configure a reverse-proxy for Pxls similar to this:
```nginx
server {
        listen          443 http2 ssl;
        server_name     example.com;
        
        ssl_certificate /path/to/fullchain.pem;
        ssl_certificate_key /path/to/privkey.pem;
        
        location /ws {
                proxy_connect_timeout 7d;
                proxy_send_timeout 7d;
                proxy_read_timeout 7d;
                proxy_pass http://localhost:4567/ws;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
        }

        location / {
                proxy_pass http://localhost:4567;
                proxy_set_header X-Forwarded-For $remote_addr;
        }
}
```

**Comment by bbdcdanilko** [comment]
> Can you elaborate what your setup is? Typically, you would configure a reverse-proxy for Pxls similar to this:
> 
> ```nginx
> server {
>         listen          443 http2 ssl;
>         server_name     example.com;
>         
>         ssl_certificate /path/to/fullchain.pem;
>         ssl_certificate_key /path/to/privkey.pem;
>         
>         location /ws {
>                 proxy_connect_timeout 7d;
>                 proxy_send_timeout 7d;
>                 proxy_read_timeout 7d;
>                 proxy_pass http://localhost:4567/ws;
>                 proxy_http_version 1.1;
>                 proxy_set_header Upgrade $http_upgrade;
>                 proxy_set_header Connection "Upgrade";
>         }
> 
>         location / {
>                 proxy_pass http://localhost:4567;
>                 proxy_set_header X-Forwarded-For $remote_addr;
>         }
> }
> ```

I did not write my setup, simply because I use the default nginx template

Now I have your nginx template, and default pxls.conf, with postgres set

The bottom line is that at the moment I want to host on my PC, and my ip (ports and ip are available from the network), this project, but globally, most likely it's not about nginx anymore, but about pxls.conf

**Comment by BlankParenthesis** [comment]
The only other required setup for Pxls should be to update the `host` and `proxy` values in the config.

**Comment by bbdcdanilko** [comment]
> The only other required setup for Pxls should be to update the `host` and `proxy` values in the config.

I hope that the last thing I would like to know from you is what to write in `host` and `proxy`, in `proxy` local IPs without a port? And in `host` 0.0.0.0? Or a real IP?

**Comment by BlankParenthesis** [comment]
If you expect others to visit your instance from the web, `host` should be your IP/domain. If you only intend on visiting it locally, `localhost` should work.

For `proxy` settings, `localhosts` of `["127.0.0.1", "0:0:0:0:0:0:0:1"]` should work and `headers` of `["X-Forwarded-For"]` should suffice.

**Comment by bbdcdanilko** [comment]
I checked it on wsl, it doesn’t work, I’ll double-check it on real Linux later

**Comment by bbdcdanilko** [comment]
This works, thank you
