### ISSUE TITLE
Discord Tags without numbers aren't supported.

### ISSUE THREAD

**Issue by loohney** [pxlsspace/Pxls#675]
When trying to fill in the "Discord Tag (Optional)" field with a new discord tag format such as "loohney" instead of "loohney#1234" it won't let me save it and it says "Discord tag contains invalid characters".

This is nothing big, but should get fixed now with the new discord tag formats.

![image](https://github.com/pxlsspace/Pxls/assets/14282703/a56507a7-1c96-4ad2-9ddf-ba00596d73ca)

**Comment by BlankParenthesis** [comment]
Hmm, I would guess this is related to the signup code maybe using a regex that was missed in the recent changes to fix this, since changing names from the settings panel seems to work. For now, I'd suggest using that as a workaround.

**Comment by loohney** [comment]
@BlankParenthesis thank you for the reply.

While browsing through the network of forks, i found this commit.
https://github.com/Nizrabed/Pxls/commit/166c5c195dfb7033367153a3d3c4f64c9c182271

**Comment by BlankParenthesis** [comment]
Yes, there is an active PR for those changes #672 but that regex looks correct for the case you're talking about before and after that change. It might be nice to fix this issue in that PR if possible though.

**Comment by loohney** [comment]
While experimenting, i noticed the commit that i posted earlier isn't doing anything. It's not even touching the regex. And it's also not even checking the regex. 

I removed `} else if (!discord.isEmpty() && !discord.matches("^.+?#\\d{4}")) {
            respond(exchange, StatusCodes.BAD_REQUEST, new space.pxls.server.packets.http.Error("bad_discord", "Discord tag contains invalid characters"));
            return;`
            
from src/main/java/space/pxls/server/WebHandler.java and its working now. Removing the #\\d{4} would also work, but would make the check obsolete, thats why i removed it entirely.
