### ISSUE TITLE
404 when GET "/"

### ISSUE THREAD

**Issue by trwy7** [pxlsspace/Pxls#701]
When attempting to connect to pxls, it fails with a "404", nothing in console or anything
![image](https://github.com/pxlsspace/Pxls/assets/47907719/8a6d489b-753e-42de-b38f-eb964eb2991e)

**Comment by VanillaSixtySix** [comment]
Hey there - make sure you're running the [front end](https://github.com/pxlsspace/pxls-web), the back end (this repo) doesn't have a response for /.
